apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-viewer
  labels:
    app: {{ .Release.Name }}-viewer
spec:
  selector:
    app: {{ .Release.Name }}-viewer
  ports:
    - port: {{ .Values.viewer.containerPort }}
      targetPort: {{ .Values.viewer.containerPort }}
  type: ClusterIP
